version: '3.3'
services:

  db:
    image: postgres:12.0
#    ports:
#      - "5432:5432"
    volumes:
      - ./persistentdata/db:/var/lib/postgresql/data
    env_file:
      - .env

  backend:
    image: sarvilin/foodgram_backend:latest
    restart: always
    volumes:
      - ./persistentdata/static:/app/static
      - ./persistentdata/media:/app/media
    depends_on:
      - db
    env_file:
      - .env

  frontend:
    image: sarvilin/foodgram_front:latest
    volumes:
      - ./frontend/:/app/result_build/
    depends_on:
      - backend

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
      - "443:443"
    restart: always
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - ./persistentdata/certbot/conf:/etc/letsencrypt
      - ./persistentdata/certbot/www:/var/www/certbot
      - ./persistentdata/static:/var/html/static
      - ./persistentdata/media:/var/html/media
      - ./docs:/usr/share/nginx/html/api/docs
      - ./docs/redoc.html:/usr/share/nginx/html/api/docs/redoc.html
      - ./docs/openapi-schema.yml:/usr/share/nginx/html/api/docs/openapi-schema.yml
    depends_on:
      - backend
      - frontend

  certbot:
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./persistentdata/certbot/conf:/etc/letsencrypt
      - ./persistentdata/certbot/www:/var/www/certbot
